version: '3.6'

services:
    splunk:
        image: splunk/splunk:latest
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=changeme
            - SPLUNK_APPS_URL=https://github.com/splunk/ethereum-basics/releases/download/latest/ethereum-basics.tgz
        ports:
            - 18000:8000
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000']
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - ./splunk.yml:/tmp/defaults/default.yml
            - /opt/splunk/var
            - /opt/splunk/etc
            - ./example-app:/opt/splunk/etc/apps/example
    ethlogger:
        image: splunkdlt/ethlogger:latest
        container_name: ethlogger
        environment:
            - COLLECT_PEER_INFO=true
            - COLLECT_PENDING_TX=true
            - ETH_RPC_URL=http://geth:8545
            - NETWORK_NAME=dev
            - START_AT_BLOCK=latest
            - SPLUNK_HEC_URL=https://splunk:8088
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_EVENTS_INDEX=main
            - SPLUNK_METRICS_INDEX=metrics
            - SPLUNK_INTERNAL_INDEX=metrics
            - SPLUNK_HEC_REJECT_INVALID_CERTS=false
            - ABI_DIR=/app/abis
            - DEBUG=ethlogger:platforms,ethlogger:eth
        volumes:
            - ./abis:/app/abis
            - ./:/app
        depends_on:
            - splunk
        restart: always
    geth:
        image: ethereum/client-go:v1.9.18
        hostname: geth
        container_name: geth
        entrypoint:
            - /bin/sh
            - -c
            - |
              geth \
                --nousb \
                --verbosity=3 \
                --ws --wsport 8546 --wsaddr "0.0.0.0" --wsorigins="*" \
                --wsapi=eth,web3,shh,net,admin \
                --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" \
                --rpcapi "eth,web3,net,admin,debug,db,shh" \
                --allow-insecure-unlock \
                --dev
        healthcheck:
            test: ["CMD", "wget", "-q", "http://localhost:8545"]
            interval: 15s
            timeout: 10s
            retries: 3
            start_period: 10s
        ports:
            - 8545:8545
            - 8546:8546
