#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ETHLOGGER_CHART_DIR="$SCRIPT_DIR/../helm/ethlogger"

tmpdir=$(mktemp -d)

trap "rm -rf $tmpdir" EXIT

render() {
  local outdir=$1

  helm template \
      ethlogger \
      --namespace ethlogger \
      --set networkName=dev \
      --set chainName=dev \
      --set fullnameOverride=ethlogger \
      --output-dir $tmpdir \
      $ETHLOGGER_CHART_DIR

  templates="configmap.yaml deployment.yaml serviceaccount.yaml"
  for f in $templates; do
	fullpath=$tmpdir/ethlogger/templates/$f

    cat $fullpath | \
        sed -e 's/[[:space:]]*$//' | \
        grep -v 'chart: ethlogger' | \
        grep -v 'namespace: ethlogger' | \
        grep -v 'heritage: Helm' | \
        grep -iv 'release: ethlogger' \
      > $outdir/$f
    echo "Wrote resource $f"
  done
  rm -rf $tmpdir/*
}

render $SCRIPT_DIR
