FROM node:12.16 as builder

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=1.41.0
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
RUN npm i -g yarn --force
RUN rustup target add wasm32-unknown-unknown
