name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/splunkdlt/connect-ci@sha256:10e6353d1bedecfb5a0100053ad0f0def1d2437e9ef79d0c3404ee877db5cad8
        steps:
            - uses: actions/checkout@v2
            - name: Build ethlogger CLI
              run: |
                  yarn install --frozen-lockfile
                  yarn build
    docker-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: splunkdlt/dlt-connect-libs/actions/build-publish-container@main
              with:
                  publish-type: pre-release
                  ghcr-org: splunkdlt
                  ghcr-release-name: ethlogger
                  ghcr-pre-release-name: ethlogger-pre
                  ghcr-user: ${{ secrets.GHCR_USER }}
                  ghcr-pat: ${{ secrets.GHCR_PAT }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    unit-tests:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/splunkdlt/connect-ci@sha256:10e6353d1bedecfb5a0100053ad0f0def1d2437e9ef79d0c3404ee877db5cad8
        steps:
            - uses: actions/checkout@v2
            - name: Run unit tests and linter
              run: |
                  yarn install --frozen-lockfile
                  yarn build
                  yarn test --verbose
              env:
                  CI: true
    check-format:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/splunkdlt/connect-ci@sha256:10e6353d1bedecfb5a0100053ad0f0def1d2437e9ef79d0c3404ee877db5cad8
        steps:
            - uses: actions/checkout@v2
            - name: Check code format
              run: |
                  yarn install --frozen-lockfile
                  yarn format:verify
              env:
                  CI: true
    check-generated-files:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/splunkdlt/connect-ci@sha256:10e6353d1bedecfb5a0100053ad0f0def1d2437e9ef79d0c3404ee877db5cad8
        steps:
            - uses: actions/checkout@v2
            - name: Check if generated files are up-to-date
              run: |
                  yarn install --frozen-lockfile
                  yarn build
                  yarn generate:all
                  echo "Checking if generated files are up-to-date"
                  git diff --exit-code
              env:
                  CI: true
    trigger-release:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/splunkdlt/connect-ci@sha256:10e6353d1bedecfb5a0100053ad0f0def1d2437e9ef79d0c3404ee877db5cad8
        needs:
            - build
            - docker-image
            - unit-tests
            - check-format
            - check-generated-files
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Semantic release
              run: |
                  yarn install --frozen-lockfile
                  yarn semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
